// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxuzAj5HuAsYXo8e0qGBJ8giDE92aiIok',
    appId: '1:614182142655:web:0e25ee410fb9ea253f7c0a',
    messagingSenderId: '614182142655',
    projectId: 'todo-96942',
    authDomain: 'todo-96942.firebaseapp.com',
    storageBucket: 'todo-96942.firebasestorage.app',
    measurementId: 'G-7ZS3MSWWB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rTI3l6fJMDFBZvMxFATGOhbbixV5G5A',
    appId: '1:614182142655:android:0329cd212c8de64e3f7c0a',
    messagingSenderId: '614182142655',
    projectId: 'todo-96942',
    storageBucket: 'todo-96942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07k9zQP93fEM4mmgWsWLdVcFDU_MpgwM',
    appId: '1:614182142655:ios:5fa8714d3386fdd63f7c0a',
    messagingSenderId: '614182142655',
    projectId: 'todo-96942',
    storageBucket: 'todo-96942.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07k9zQP93fEM4mmgWsWLdVcFDU_MpgwM',
    appId: '1:614182142655:ios:5fa8714d3386fdd63f7c0a',
    messagingSenderId: '614182142655',
    projectId: 'todo-96942',
    storageBucket: 'todo-96942.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxuzAj5HuAsYXo8e0qGBJ8giDE92aiIok',
    appId: '1:614182142655:web:3f46cace850efc5d3f7c0a',
    messagingSenderId: '614182142655',
    projectId: 'todo-96942',
    authDomain: 'todo-96942.firebaseapp.com',
    storageBucket: 'todo-96942.firebasestorage.app',
    measurementId: 'G-5T4LRJ0CYD',
  );
}
